export default [
{
  id: 1,
  name: 'Showcase: Jake Bailey',
  image: 'http://i.imgur.com/ZvN3Q7l.jpg',
  introduction1: 'I can listen to Jake Bailey talk about beer for hours on end; it’s easy to lose time listening to a southern twang wax poetic about the latest iteration of a Dupont saison. I’ve frequently witnessed him behind the bar of Taproom No.307 with a glass of beer held high into the light and customers rapt with attention as he explains the texture and complexity of a fine creation. He may very well be divining the universe with that glass, for all the intensity his gaze supplies.',
  introduction2: 'As many a transplant before him, Jake came from Montgomery, Alabama with a tune in his heart and a guitar on his back. He started off at Panera Bread in Astoria, then as a server at a few places until he managed his sneak his way behind a Midtown bar. Today you’ll find him at Taproom No.307, groomed to look like the quintessential craft beer bartender - long hair tied up in a bun, thick beard, the occasional frames, and a somewhat serious, straight-forward, yet pleasant persona. I’ve stolen a couple hours out of his day to hear more about beer, homebrewing, and stock trading, so without further ado let’s hear from the bartender himself.',
  question1a: 'Tell me a little about yourself:',
  question1b: 'Where are you from?',
  answer1b: 'Montgomery, Alabama',
  question1c: 'What did you think you were going to be when you grew up?',
  answer1c: 'At 5, I thought I’d like to be Crash Bandicoot. Later, a radiologist because doctors make money, and x-rays are cool. In 9th grade, I wrote a 10-page essay on drug trafficking, which led me to think pharmacology or herbology would be cool. I like to make things with my hands and I enjoy the whole process of creation. In college, I thought I could be a music producer/rapper. At the University of Alabama, they didn’t offer the type of music program I was looking for, so I joined the interdisciplinary program which allowed me to structure my own curriculum. There weren’t many resources at school, so it was a lot of studying outside of school. It’s also the reason why I moved to New York City.',
  question1d: 'What’s your favorite curse word?',
  answer1d: 'Ass-spelunker',
  question1e: 'What’s your favorite alcohol-related book?',
  answer1e: '“The Complete Beer Course”, by Joshua Bernstein',
  question1f: 'What else do you enjoy doing outside of work?',
  answer1f: 'Trading stocks, homebrewing, and self-learning. I just finished reading “The Republic”, by Plato, and right now I’m into a couple books that are really different from one another - “The Astrology of Fate” and "I Will Teach You to Be Rich".',
  question2a: 'Tell me a little about your current bartending gig:',
  question2b: 'How long have you been there?',
  answer2b: '3 years. Everyone is very nice, the clientele included. The craft beer is great - there’s 40 beers on tap and one in the cask. The craft beer is mainly what keeps me there, because I have such a passion for it. I’ve also been collaborating with the rest of the Tap team on the cocktail menu, which changes seasonally. The newest cocktail menu just came out and I made this cocktail called “The Boozy Bastard”, which contains: 1 oz white whiskey (High West Silver), 1 oz rye whiskey (JP Wiser), 1/2 oz Montenegro Amaro, 1/2 oz Carpano Antica Sweet Vermouth, 1/2 oz Dolin Extra Dry Vermouth, stir in ice, pour over a chilled coupe glass, and zest with lemon and orange.',
  question2c: 'Any special perks?',
  answer2c: 'Beer festival at the Armory at Park Ave and 26th St- Taproom has participated in the festival about 4 times. The beer rewards program - this isn’t used very often, the coolest one is to make your own beer at a small brewery and  Taproom will put it on a tapline. The Taproom 307 team went to Strong Rope brewery in Brooklyn last year (around January) and made their own beer called “I’d Tap That”. The beer was an India Red Ale - hoppy red ale, malt backbone to it, good amount of bitterness. Beer Baptisms - drinks are included, free drinks for friends, food, and a large tub filled with beer wherein the customer dunks her head into the tub and is then baptized in the name of Beer. It’s happened about three times in the last three years.',
  question3a: 'Do you remember your first sip of alcohol?',
  answer3a: 'Sipping on dad’s beer while grilling as a kid.',
  question4a: 'If you had to choose only six bottles for your bar, what would those bottles be?',
  answer4a: 'Knob Creek, Ilegal Mezcal Reposado, Montenegro Amaro, Brooklyn Gin, Carpano Antica Sweet Vermouth, Green Chartreuse',
  question5a: 'What was your first bartending gig?',
  answer5a: 'Bottomz Up - sports bar in midtown. (Samantha: And that’s with a ‘Z’, right?) Yes, with a ‘Z’ - you think that’s funny, right. Started off as a server in a newly opened restaurant; the bartender on duty got really swamped, so I jumped back there after permission from said bartender. Started off making vodka sodas and pouring beers and I stayed for around 9 - 10 months.',
  question6a: 'When you visualize your dream shift, what playlist is in the background?',
  answer6a: '80s dance hall reggae',
  question7a: 'What’s your favorite classic cocktail?',
  answer7a: 'The Boulevardier',
  question8a: 'What’s your favorite beer to go with a class burger and fries?',
  answer8a: 'The Dupont saison; it’s a light-bodied Belgian saison. Very soft, not dry, light and airy, doesn’t leave a lot of residual sugar. Grassy framework (esters) for a golden Belgian. Just picture this - in between burger bites, take a sip of that light, aromatic saison to prepare yourself for the next big bite of that meaty, juicy burger.',
  question9a: 'Advice section:',
  question9b: 'What advice would you give to someone starting off in this industry?',
  answer9b: 'Use both hands! (I’ve heard that many times from you.) It’s essential, you’ll literally double your speed. It’s a gradual process- you learn how to do one thing, then you learn how to do another. At a certain point, the first thing becomes instinct, while the second one you’re actively working on is learning. Don’t get wasted - or, know your limit if you do start drinking behind the bar. Keep a cool head.',
  question9c: 'What are the most popular cocktails you make?',
  answer9c: 'Old-fashioneds, margaritas, and martinis. People are now turning away from super-sweet drinks like bay breezes, sea breezes, and sex on the beach.',
  question9d: 'What are the most popular types of beer you get asked about?',
  answer9d: 'People’s favorite adjective is “light”, and as a bartender, you must ask more questions about what the customer really means. “Light” for some people means a pilsner, for other it may mean a wheat beer, another person may think about IPA.',
  question9e: 'Has it ever been difficult for you to be social with your customers? If so, what have you done to improve your social skills?',
  answer9e: 'Being social has never really been difficult, but after being there for three years, I feel like the bar at Taproom is another extension of home. Being there for so long has created these last relationships with coworkers and clientele.',
  question9f: 'What’s the most difficult part of your job?',
  answer9f: 'Always running out of things, keeping things stocked - liquor, glassware, which boils down to managerial issues. Improvising in the moment - when can I do at that moment to make things happen and make the customer happy?',
  question9g: 'What does your speed rack look like (from left to right)?',
  answer9g: 'Vodka, gin, rum, tequila, triple-sec, whiskey, and agave syrup. Don’t fuck with a bartender’s speed rack!',
  question10a: 'What are your customer pet peeves?',
  answer10a: 'Far and away, number one is when customers start asking for free shit. Also, when you have your hand out waiting for cash or a credit card and the customer slaps it on the bar instead of placing it on your hand.'
},

{
  id: 2,
  name: 'Showcase: Becca Smith',
  image: '',
  introduction1: '',
  introduction2: '',
  question1a: 'Tell me a little about yourself:',
  question1b: 'Where are you from?',
  answer1b: 'Born and raised Long Island, New York. I moved to New Jersey when I was a sophomore in high school, I just turned 16. It was tough because I moved away from all of my friends and everything I knew, my parents were splitting up and I didn’t know whether to be angry or sad about it.',
  question1c: 'What did you think you were going to be when you grew up?',
  answer1c: 'There was two things I was possibly going to be: either a Broadway singer/actress or I was going to be a professional ice skater. When I was a kid I had my own skates and it was something I was into for awhile, I even had an ice skating party.',
  question1d: 'What’s your favorite curse word?',
  answer1d: 'Malaka!',
  question1e: 'What’s your favorite alcohol-related book?',
  answer1e: 'I really enjoyed The Basketball Diaries, although it was mainly about drugs but it did start off with alcohol. That was the first time I read the book before watching the movie.',
  question1f: 'What else do you enjoy doing outside of work?',
  answer1f: 'I really enjoy cooking and trying new dishes. I like hiking and biking; I love movies',
  question2a: 'Tell me a little about your current/last bartending gig:',
  question2b: 'How long have you been there?',
  answer2b: 'My last bartending gig was my first bartending gig in Colorado, and I was wondering what it would be like in comparison to New York. The bar that I happened to work at was more of like a blue-collar, working-class bar/restaurant and it was kind of an interesting time because the town that it’s in doesn’t have late-night bars open. It was the first bar in that town to have late-night hours, and I helped open that bar. I hate to be one of those people that brings up 9/11, but around that time things changed a lot in regards to how people made money. I was working as a producer on TV commercials, the visual graphics side of it, working full-time, benefits, 60k. Slowly but surely they started hiring freelance, contract people (hired for a month or two, then they had to find another job). Once that started happening, I decided to move on and started waitressing and bartending. This was around 2004/2005.',
  question2c: 'Any special perks?',
  answer2c: '',
  question3a: 'Do you remember your first sip of alcohol?',
  answer3a: 'During holidays, my dad would put his pinky in his drink and then let us kids try alcohol. I remember the first time actually trying to drink alcohol, it was Christmas, maybe I was 13 or 14, and this was the first year my cousin and I were allowed to stay up with the adults. Apparently, after the kids are put to sleep, the adults just got hammered. The first time I actually drank drank was the night before the Puerto Rican Day Parade and I was hanging out with my cousin and some older guys. We had 40s, and I was just kind of sipping slow and felt embarrassed so I started chugging. Let me tell you, don’t start chugging 40oz beers. When my aunt found out, she was trying to hide it from my mother because I got drunk under her watch',
  question4a: 'If you had to choose only six bottles for your bar, what would those bottles be?',
  answer4a: 'They have to be the best of the best. Porfilio Cactus reposado (tequila, you can only find it in Mexico. The bottle is glass-blown, and once you drink the bottle you’ll see there’s a little cactus within the make of the bottle), Golden Moon Gin ( a gin that’s distilled in Golden, Colorado, lots of lavender in it), Kraken Rum (it’s a little bit cheaper than some other rums, but I can drink that straight), I like Ketel for my vodka, for my whiskey I’ll choose Stag Junior (it’s a higher end whiskey, but the baby version of it - it tastes super high end but it’s more affordable). I’d want a good bubbly - I’d probably want a Moet in my bar, and lastly, St. Germain.',
  question5a: 'What was your first bartending gig?',
  answer5a: 'My first official bartending gig was at Gleeson’s in Astoria, and the way I got that job was that I met the owner at another bar having a drink and I told him I was a waitress/bartender. There was some kind of UFC fight and we exchanged numbers in case he needed someone. A week later, he called me a few hours before the shift started. One night we had a party downstairs, and we were short a bartender so I kind of lied my way into my first bartending gig. The people at the party loved me, they told the boss. After that, they gave me my first official bartending shift - Monday night happy hour, and then I just started taking all the shifts people didn’t want. That was probably the last time I was officially hired as a server.',
  question6a: 'When you visualize your dream shift, what playlist is in the background?',
  answer6a: 'I guess it depends on the place I’m working at. If I’m at a pub, it would be more rock stuff. But when I was working at Ovelia (Greek restaurant in Astoria), I’d be playing Flight Facilities.',
  question7a: 'What’s your favorite classic cocktail?',
  answer7a: 'The Sidecar. I love it because it’s fancy but it’s not a “foo-foo” drink - or rather, it looks “foo-foo” but it has a punch and it’s one of those classic drinks that people have forgotten about.',
  question8a: 'What’s your favorite beer to go with a classic burger and fries?',
  answer8a: 'Oh man, I get fun of all the time here, especially because Colorado is the craft beer capital of the world. But with a burger, I’d want a crisp, cold Miller Light or a Carlsberg.',
  question9a: 'Advice section:',
  question9b: 'What advice would you give to someone starting off in this industry?',
  answer9b: 'A couple of words of advice that I give to anyone that I’m training is to set up your bar thinking that a million people are going to come by. Even if it’s a Monday night, set it up like it’s a Friday night. Act as if it’s the busiest night of your life - be prepared! When a customer asks for a drink, never tell them you don’t know what they’re talking about. I usually say, “It’s been awhile since I’ve made that,” or something to that effect, and have the customer clarify the ingredients. The other suggestion that worked for me - when I was starting out, I really just paid attention to the people that I was working with, their techniques. You basically steal people’s techniques in regard to drink-making and customer interaction until you’ve grown your own. The last thing I would say is: people think that bartending it easy, but it sells itself. Alcohol sells itself, so that that’s easy. The hard part is separating yourself from other bartenders and other bars - what makes people want to come to your bar and see you? For anyone that is thinking of becoming a bartender, you really have to keep in mind what exactly it is that you’re doing. People hired you to sell their products at their store, so you should go in everyday like you’re going to sell cars. Not just selling the product, but you’re also selling the time. Being in a good mood is huge to making money - if you’re going to be in a stinky mood and not interact with people, than don’t be a bartender. Starting off as a server does help when starting off - learning all the cocktails. Serving helps you learn how to deal with the customers, because bar customers can be a little more aggressive than bar customers so starting off there will be a little more helpful in the long run.',
  question9c: 'What are the most popular cocktails you make?',
  answer9c: 'That’s kind of something that’s always changing throughout the years, but I will say for a long-time picklebacks were a big deal. I would always need pickle juice behind the bar to be prepared. The “bomb” shots with red bull are always popular. I’ve noticed more whiskey bars opening in this area (Boulder), where more classic cocktails like old-fashioneds and negronis are very popular. The Salty Dog has been a thing lately.',
  question9d: 'What are the most popular types of beer you get asked about?',
  answer9d: 'You need to be able to explain the difference between a pilsner or an ale versus like a stout or a porter. The most common beers ordered are pilsners and ales. Out here in Colorado the beer situation is kind of intense - there’s literally a term called “beer tender”; these guys only know about beer and nothing about liquor. Even though Colorado is huge on craft beer, domestic beers are very popular as well. Working class guys at the end of the day just want a light, crisp beer.',
  question9e: 'Has it ever been difficult for you to be social with your customers? If so, what have you done to improve your social skills?',
  answer9e: 'This is difficult because even someone like me that is very social, and is easy to talk to, there’s always going to be a customer where the conversation flows easily. It’s hard to figure out what to do when the conversation gets awkward or you don’t know what to say. When it’s a slow night and there’s only a couple of people at the bar, no one really wants to just sit in silence. I just try to think of basic questions, “Do you live around here?” “What do you do for a living?” “Have you been here before?” Basically, you provide an opening for them to talk. People usually enjoy talking about themselves, so providing that window and knowing how to redirect the conversation when it gets awkward is essential.',
  question9f: 'What’s the most difficult part of your job?',
  answer9f: 'The most difficult part of bartending is, I feel, dealing with drunk people at the end of the night - they either get aggressive, or think they know more than I do. It’s just a part of the job where you need to make sure you’re not over-serving people. It can be quite uncomfortable explaining to an adult why they shouldn’t have more to drink. If I’m working with my male partner behind the bar, and I tell the customer that he can’t have enough, the customer may insult me, but if one of the guy’s may say it it may come across better just because it’s another man saying it. It’s definitely an issue. Working at late-night bars, they usually try to schedule a man there just in case anything happens. It’s the world we live in.',
  question9g: 'What does your speed rack look like (from left to right)?',
  answer9g: 'Again, this depends on where I’m at and what I’m selling most, but usually I’ll start with my lighter liquors and move to the darks. Vodka, gin, white rum (if I have it), dark rum, whiskey, and then all the additives (lime juice, triple-sec).',
  question10a: 'What are your customer pet peeves?',
  answer10a: 'I hate when they ask for the strongest drink I can make. I hate when they ask if they can get something for free. I hate when they tell me how to do my job - I know a lot of people drink, but not a lot of people know how to tend bar.'
},

{
 id: 3,
  name: 'Showcase: Daisy Salas',
   image: '',
  introduction1: '',
  introduction2: '',
  question1a: 'Tell me a little about yourself:',
  question1b: 'Where are you from?',
  answer1b: 'Los Angeles, California',
  question1c: 'What did you think you were going to be when you grew up?',
  answer1c: 'A school teacher or counselor.',
  question1d: 'What’s your favorite curse word?',
  answer1d: 'Shit',
  question1e: 'What’s your favorite alcohol-related book?',
  answer1e: 'I don’t read very many “alcohol-related book”... I’ve read books in which alcohol drinking is involved... I would have to say Richard Matheson’s I Am Legend. Who would not love a Whiskey drinking man in the middle of a vampire apocalypse?',
  question1f: 'What else do you enjoy doing outside of work?',
  answer1f: 'Playing music, gardening, attending art and music events, and exploring LA’s newest restaurants and breweries.',
  question2a: 'Tell me a little about your current/last bartending gig:',
  question2b: 'How long have you been there?',
  answer2b: 'I have not worked in a restaurant or bar in about 3 years because I decided to go back to school full time. With the knowledge that I have of bartending at bars, restaurants, and catering events, I decided to work on as a freelance bartender for private parties and weddings. I have been doing this for the past 3 years and have really enjoyed being my own boss.',
  question2c: 'Any special perks?',
  answer2c: 'As a freelance bartender I get to set my own price and hours. I get to decide what I want to wear and get to set up my bar exactly how I want it. I am able to network with new people to get new potential gigs in the future. Almost all of the time the host brings me food, coffee, cake, or whatever else is being served at the event. Most importantly I get to be myself without having to worry about meeting any standards or quota. ',
  question3a: 'Do you remember your first sip of alcohol?',
  answer3a: 'Yes, I was at a backyard punk rock show in East Los Angeles. The place was packed and there was two full kegs of Bud Light. I was there with my older sister and her group of friends who were already drinking when my sister and I arrived. They pressured me into drinking some beer from a solo cup and when I took the first sip I thought it was the most disgusting thing I had ever tasted. That being said, I drank about 4 solo cups of Bud Light and felt equally buzz and cool... good times.',
  question4a: 'If you had to choose only six bottles for your bar, what would those bottles be?',
  answer4a: 'Bulleit Bourbon, Dewar’s Blended Scotch, Corzo Reposado Tequila, Ketel One Vodka, St. Germaine, Bitters ',
  question5a: 'What was your first bartending gig?',
  answer5a: 'I worked at Chili’s Grill and Bar for about 2 years as a server before moving up to a bartender position. That was where I got my first experience as a bartender.',
  question6a: 'When you visualize your dream shift, what playlist is in the background?',
  answer6a: 'My dream shift would be in a calm and cool environment, kind of like a speakeasy feel. I would love to have some easy going music like some Billie Holiday, Ella Fitzgerald, and Louis Armstrong. As I get older I prefer shifts that are calm and fun, unlike when I was a younger bartender… that would have definitely been a riot grrl/90’s rock shift.',
  question7a: 'What’s your favorite classic cocktail?',
  answer7a: 'Old-fashioned.',
  question8a: 'What’s your favorite beer to go with a classic burger and fries?',
  answer8a: 'We have an amazing burger joint in Los Angeles that serves 100% grass fed beef burgers and what’s even more amazing about this place is that it is located in a family owned liquor warehouse. Normally when I get a burger and fries I make sure to pick up a six pack of Mama’s Little Yella Pils, a crisp and refreshing pilsner from Colorado.',
  question9a: 'Advice section:',
  question9b: 'What advice would you give to someone starting off in this industry?',
  answer9b: 'I would advise people who are starting off by getting their foot in the door by starting off as a server or a cocktail server, and working your way up. Rather than going to bartending school, which doesn’t give you work experience. A lot of the times employers aren’t looking for bar knowledge but rather bar working experience. Start off somewhere where they can move up and learn the ropes from the ground up.',
  question9c: 'What are the most popular cocktails you make?',
  answer9c: 'It depends on the clientele for private parties. Margaritas are very popular because it’s LA; old-fashioneds, too. I’ve noticed a decline in super-sweet drinks since stronger drinks are preferred nowadays (like whiskey and tequila forward drinks).',
  question9d: 'What are the most popular types of beer you get asked about?',
  answer9d: 'A lot of people are into IPAs and saisons right now - it’s something different, and they’re hip. If you go to the local breweries in LA, you’ll see everything - lagers, ales, wheat. Sours are weird but are getting pretty hip, too.',
  question9e: 'Has it ever been difficult for you to be social with your customers? If so, what have you done to improve your social skills?',
  answer9e: ' I think my first time being behind the bar was a little scary, because you don’t know what to expect. When I started at Chili’s, they suggested, “If you have nothing to talk about, maybe you can talk about a sport or whatever is on TV.” “Ask the person what they’re up to.” “Tell them a little about yourself.” I think the best advice is just to be yourself and share a little about yourself, because a lot of the customers are either regulars or want to be regulars and want to be able to get to know you.',
  question9f: 'What’s the most difficult part of your job?',
  answer9f: 'I would say the long hours, sometimes, the late shifts. The hardest part would be, as a female bartender, is cutting off people when they’re at that point when they need to be cut off. I think with male bartenders it may be a little different, but as a female, for people to accept being cut off without starting an arguement with you.',
  question9g: 'What does your speed rack look like (from left to right)?',
  answer9g: 'If I have a table set up, the ice would be under the table or to my right. Liquor would be to my right, and mixers would be to my left.',
  question10a: 'What are your customer pet peeves?',
  answer10a: 'When customers go to the bar and they don’t know what they want - when you have a lot of people waiting to order, but you still try to be super nice and make suggestions but they aren’t taking any of them. It’s like one of the times when you’re smiling really big and your toes are clenching and you’re just thinking, “Hurry up!”'
}

];









